### PR TITLE
Fix the filed name in `showSaveFilePicker` options

### PR DESCRIPTION
**Pull request by garsue**
Now `types` is the correct field name, not `accepts`.
https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker#parameters

### CODE REVIEW

**Comment by jimmywarting** [comment]
`d.ts` is generated by the JSDocs.
so that should be changed instead.

**Comment by garsue** [comment]
After fixing JSDoc, I ran `npm run _prepublishOnly` and re-generated the `d.ts`.
As a result, unrelated files were also changed, but I committed them as well.

**Comment by jimmywarting** [comment]
Thanks, that's fine

**Comment by linonetwo** [comment]
I think showOpenFilePicker also needs to be changed https://github.com/jimmywarting/native-file-system-adapter/issues/57#issuecomment-1531104602

And this seems not released in v3.0.0

**Pull request merged**
